### ISSUE TITLE
would be possible to avoid => REMOVE ,  ALL default values in any of the modules ?

### ISSUE THREAD

**Issue by eugsim1** [oracle-terraform-modules/terraform-oci-vcn#15]
Hello
For an internal project i had to use some of the modules, the variables of many of the modules have already "default" values deep inside the variables.tf and if for some reason users they have derived code from these modules then the defaults values are used and  in some conditions this can leed to errors and endless hours of debugging to understand why a value was wrong.
Removing ALL DEFAULTS VALUES will fail the terraform scrips EXPLICITLY and then the user will be able to update them to a terrafromtf.vars file this will help us to speed up with the re utilisation of the modules instead of trying to debug  :(
Thanks
Eugene

**Comment by hyder** [comment]
Can you please elaborate?

**Comment by kral2** [comment]
Agree there is a need to clean "some" defaults from the module, if they introduce configuration rather than behavior.
Yet, I think we can't just remove all defaults without distinction. Some of them can have legitimate reasons to be there:

- keep input as optional -> we should probably not change an optional argument from provider and artificially transform it to required,
- implement default behaviors that are in line with good practices,
- having more concise module block by default.

That being said, if ANY default value is set by the module, we should definitely document it and always give option to the module user to potentially change the value.
